pipeline {

  environment {
    KUBECONFIG = credentials('kuberneteskey')
    
  }

  agent any

  stages {


    stage('Deploying to Kubernetes') {
      steps {
        script {
          sh 'kubectl apply -f deployment.yml'
        }
      }
    }

  }

}
